### ISSUE TITLE
Modelo de una Ruta

### ISSUE THREAD

**Issue by JaimeGM96** [pedrooot/OnTime#10]
Tal y como se describe en el milestone [M1](https://github.com/pedromarting3/OnTime/milestone/1) se necesitan unas estructuras de datos para representar el modelo de la ciudad. Fijandonos en lo que se comenta en las historias de usuario https://github.com/pedromarting3/OnTime/issues/5 y https://github.com/pedromarting3/OnTime/issues/6 una de ellas puede ser una Ruta. ¿Cómo sería la estructura de una Ruta?

**Comment by pedrooot** [comment]
Buenas @JaimeGM96 tras estar implementando el objetivo 2 he cambiado de perspectiva a la hora de modelizar el problema. Realmente no necesitamos un id para la ruta porque se puede identificar a partir de su nombre por lo que eliminaría ese atributo. Por lo demás no se me ocurre actualmente otros atributos que necesitemos.

**Comment by JaimeGM96** [comment]
Lo quitamos 👍🏼

**Comment by JJ** [comment]
No plantea un problema, sino una solución. Los issues son para problemas, el código para soluciones. Tampoco enlaza ninguna historia de usuario. Por favor, revisad los objetivos de aprendizaje de las semanas 6 y 7 para ver cómo se plantea un issue.

**Comment by JaimeGM96** [comment]
He reescrito la descripción de este issue planteando primero el problema que tenemos y posteriormente proponiendo una posible solución.

**Comment by JJ** [comment]
No está asignado a ninguna HU ni plantea un problema, sino la creación de una clase sin aparente relación con ninguna hU.

**Comment by pedrooot** [comment]
En el #9 acordamos añadir un atributo a la ruta que es el numero de paradas. Este atributo simplemente toma el valor del número de tramos que haya en la ruta. Deberíamos de añadirlo.

**Comment by JaimeGM96** [comment]
Ya está actualizado.

**Comment by JaimeGM96** [comment]
Habiendo recopilado información, finalmente la clase ruta propuesta sería la siguiente:
- Nombre
- Numero de paradas
- Tramos
- Matricula vehículo

**Comment by JJ** [comment]
> Finalmente la clase ruta que hemos acordado sería la siguiente:
> 
>     * Nombre
> 
>     * Numero de paradas
> 
>     * Tramos
> 
>     * Matricula vehículo

¿Si dos vehículos siguen la misma ruta, hay que crear dos objetos valor diferentes?

Además, creo que no me estáis entendiendo. El *product manager* no *acuerda* nada con la persona que desarrolla. Para eso, ya puede desarrollarlo él o ella. El que desarrolla propone unos cambios y el product manager decide si le sirven o no para la lógica de negocio. Si no sirven, tendrá que decir qué necesita tener la lógica de negocio.

**Comment by JaimeGM96** [comment]
El caso donde se crearían dos objetos valor diferentes sería que partiesen desde el mismo sitio, dos coches exactamente iguales ya que el consumo tiene que ser el mismo para que se de ese caso.

**Comment by JJ** [comment]
E issue sigue sin plantear un problema, y sin enlazar en el cuerpo la historia de usuario. 
Por favor, tratad de seguir la metodología que se ha indicado en clase y en los diferentes documentos: guión, errores frecuentes, y explicaciones en clase.

**Comment by JJ** [comment]
> No plantea un problema, sino una solución. Los issues son para problemas, el código para soluciones. Tampoco enlaza ninguna historia de usuario. Por favor, revisad los objetivos de aprendizaje de las semanas 6 y 7 para ver cómo se plantea un issue.

Y esto ya lo dije hace tres días.

**Comment by JaimeGM96** [comment]
Pero el problema lo he planteado en otro issue y he comentado estos como las soluciones a ese problema, ¿eso no es correcto?

**Comment by JJ** [comment]
Mira los objetivos de aprendizaje de esta semana y la anterior. Mira el guión de este objetivo. Mira los errores frecuentes. O lo que ya te he comentado varias veces en este mismo issue.
Si un issue no plantea un problema o no se refiere a una historia de usuario, no es que sea incorrecto, es que ni siquiera es un issue. Si haces commits refiriéndote a ese issue, no es que sean incorrectos, es que simplemente no estás haciendo nada.
Por favor, trata de consultar el material que se ha hecho o simplemente hacer caso a las cosas que se te comentan aquí para comprender qué es lo que hay que *hacer*, no lo que hay que *escribir*

**Comment by JaimeGM96** [comment]
Si he entendido correctamente todo, los issues ya plantean un problema.

**Comment by JJ** [comment]
¿Y eso es lo que has usado para el desarrollo, haciéndolo desde cero ?
