### ISSUE TITLE
Modelo de un Tramo

### ISSUE THREAD

**Issue by JaimeGM96** [pedrooot/OnTime#11]
Como ya se ha comentado en el issue #10, viendo lo descrito en el milestone [M1](https://github.com/pedromarting3/OnTime/milestone/1) se necesitan unas estructuras de datos para representar el modelo de la ciudad. Tras analizar las historias de usuario https://github.com/pedromarting3/OnTime/issues/5 y https://github.com/pedromarting3/OnTime/issues/6 el siguiente modelo a representar puede ser un Tramo. ¿Cómo sería la estructura de un Tramo?

**Comment by pedrooot** [comment]
¿A qué te refieres con el último atributo? El de la inicio de hora en el día. El resto tiene buena pinta

**Comment by JaimeGM96** [comment]
Con ese atributo sabremos la hora del día en el que se ha realizado la ruta. No es lo mismo entrar a Granada a las 8 de la mañana que a las 7 de la tarde, el tráfico varia por lo que se tarda más.

**Comment by pedrooot** [comment]
Aaaa vale vale perfecto

**Comment by JaimeGM96** [comment]
¿Es necesario que en el tramo esté el atributo de consumo medio? Teniendo en cuenta que el consumo depende del vehículo y esa información ya está almacenada en él.

**Comment by pedrooot** [comment]
Tienes razón, en un futuro podríamos tomar el consumo medio del vehículo y a partir del mismo calcular el consumo del vehículo en determinada ruta/tramo. El atributo consumo medio del tramo no es necesario @JaimeGM96

**Comment by JaimeGM96** [comment]
Eliminado 👍🏼

**Comment by JaimeGM96** [comment]
La clase Tramo que nos queda después de analizar el problema sería la siguiente:
- Id
- Origen
- Destino
- Distancia
- Tiempo medio
- Hora inicio

**Comment by JaimeGM96** [comment]
Propongo que para la clase Tramo se elimine el Id ya que se puede diferenciar un tramo de otro con los atributos origen, destino y hora inicio.
