### ISSUE TITLE
Modelo de un Vehículo

### ISSUE THREAD

**Issue by JaimeGM96** [pedrooot/OnTime#12]
Otro de los modelos que se necesitan para representar la estructura de la ciudad comentada en [M1](https://github.com/pedromarting3/OnTime/milestone/1) es el Vehículo.

Ya hemos visto en las historias de usuario [HU1](https://github.com/pedromarting3/OnTime/issues/5) y [HU2](https://github.com/pedromarting3/OnTime/issues/6) que el objetivo es coordinar mejor el tráfico y conociendo bien como son los causantes del problema (Vehículos) se podrá entender y alcanzar la solución.

¿Cuál es la información que se almacenaría de los mismos?

**Comment by pedrooot** [comment]
Me parece muy buena idea el atributo de la antigüedad pero si realmente quieres implementarlo así también tendríamos que manejarlo de alguna forma en la ruta/tramos para determinar la edad de los vehículos que pueden entrar en los mismos. Esto hace referencia a #10 y #11

**Comment by JaimeGM96** [comment]
Podríamos poner como referencia en la clase Tramo el vehículo para poder obtener así sus datos. Con ponerlo en la clase Tramo sería suficiente porque es donde se necesita saber cual elegir.

**Comment by pedrooot** [comment]
Te entiendo, además una ruta puede tener tramos que pertenezcan a una antigüedad, otros a otra...  
Concuerdo contigo @JaimeGM96 !!

**Comment by JaimeGM96** [comment]
La clase Vehículo quedaría finalmente de la siguiente forma:
- Matricula
- Antigüedad
- Consumo medio
