### ISSUE TITLE
[HU1] ¿Qué es una Ruta?

### ISSUE THREAD

**Issue by JaimeGM96** [pedrooot/OnTime#19]
Tal y como se describe en el milestone [M1](https://github.com/pedromarting3/OnTime/milestone/1) se necesitan unas estructuras de datos para representar el modelo de la ciudad. Fijandonos en lo que se comenta en las historias de usuario https://github.com/pedromarting3/OnTime/issues/5 y https://github.com/pedromarting3/OnTime/issues/6 una de ellas puede ser una Ruta. ¿Cómo sería la estructura de una Ruta?

**Comment by JaimeGM96** [comment]
He considerado que los atributos de la clase Ruta que almacene los datos de la misma podrían ser los siguientes:

- Id para indentificar las diferentes rutas
- Nombre
- Tramos que será un array de los tramos que forman la ruta

¿Serían necesarios más atributos para la Ruta?

**Comment by JaimeGM96** [comment]
Buenas @JaimeGM96 tras estar implementando el objetivo 2 he cambiado de perspectiva a la hora de modelizar el problema. Realmente no necesitamos un id para la ruta porque se puede identificar a partir de su nombre por lo que eliminaría ese atributo. Por lo demás no se me ocurre actualmente otros atributos que necesitemos.

_Originally posted by @pedromarting3 in https://github.com/pedromarting3/OnTime/issues/10#issuecomment-1291728990_

**Comment by JaimeGM96** [comment]
Lo quitamos 👍🏼

_Originally posted by @JaimeGM96 in https://github.com/pedromarting3/OnTime/issues/10#issuecomment-1291749443_

**Comment by JaimeGM96** [comment]
No plantea un problema, sino una solución. Los issues son para problemas, el código para soluciones. Tampoco enlaza ninguna historia de usuario. Por favor, revisad los objetivos de aprendizaje de las semanas 6 y 7 para ver cómo se plantea un issue.

_Originally posted by @JJ in https://github.com/pedromarting3/OnTime/issues/10#issuecomment-1291883783_

**Comment by JaimeGM96** [comment]
He reescrito la descripción de este issue planteando primero el problema que tenemos y posteriormente proponiendo una posible solución.

_Originally posted by @JaimeGM96 in https://github.com/pedromarting3/OnTime/issues/10#issuecomment-1293161075_

**Comment by JaimeGM96** [comment]
No está asignado a ninguna HU ni plantea un problema, sino la creación de una clase sin aparente relación con ninguna hU.

_Originally posted by @JJ in https://github.com/pedromarting3/OnTime/issues/10#issuecomment-1293704223_

**Comment by JaimeGM96** [comment]
En el #9 acordamos añadir un atributo a la ruta que es el numero de paradas. Este atributo simplemente toma el valor del número de tramos que haya en la ruta. Deberíamos de añadirlo.

_Originally posted by @pedromarting3 in https://github.com/pedromarting3/OnTime/issues/10#issuecomment-1294855211_

**Comment by JaimeGM96** [comment]
Habiendo recopilado información, finalmente la clase ruta propuesta sería la siguiente:
- Nombre
- Numero de paradas
- Tramos
- Matricula vehículo

_Originally posted by @JaimeGM96 in https://github.com/pedromarting3/OnTime/issues/10#issuecomment-1294871272_

**Comment by JJ** [comment]
Creo que ya lo he dicho una vez u otra, pero lo repito.

*No hay que proponer absolutamente nada* en el issue

(Y por supuesto, no tiene que aprobarlo @pedromarting3 )

Lo que se hace es que, referenciando este issue, se crea código que resuelva el problema en los términos que ha sido planteado. Y @pedromarting3 decide si es adecuado para su lógica de negocio o no; si no lo es, lo explica o modifica su documentación (historia de usuario y milestone)

¿No os dais cuenta que si se hiciera así en la empresa sería una pérdida de tiempo? La metodología es la que dice si algo está bien, y la forma como se expresan los requisitos, *no* la persona o personas.

**Comment by pedrooot** [comment]
Buenas @JaimeGM96 pienso que con la estructura actual de clases no se implementaría la lógica de negocio ya que estás proponiéndome una serie de clases que sirven para representar los diferentes elementos que tenemos pero ninguna que haga esa "búsqueda optimizada" que necesitamos. Teniendo en cuenta lo actual, me gustaría que me propusieses una clase nueva que haga esa "búsqueda".  
Realmente no es necesario que en el objetivo 2 implementes TODAS las clases necesarias, simplemente debes especificar en el PR en cuáles te vas a centrar.

**Comment by JJ** [comment]
> Buenas @JaimeGM96 pienso que con la estructura actual de clases no se implementaría la lógica de negocio ya que estás proponiéndome una serie de clases que sirven para representar los diferentes elementos que tenemos pero ninguna que haga esa "búsqueda optimizada" que necesitamos. Teniendo en cuenta lo actual, me gustaría que me propusieses una clase nueva que haga esa "búsqueda". Realmente no es necesario que en el objetivo 2 implementes TODAS las clases necesarias, simplemente debes especificar en el PR en cuáles te vas a centrar.

Y por esto es por lo que hay que plantear un problema, y no proponer una estructura de clases.

**Comment by JaimeGM96** [comment]
Lo siento pero no comprendo bien, tengo una serie de dudas y me gustaría aclararlas. En el Milestone 1 [M1](https://github.com/pedromarting3/OnTime/milestone/1) se habla de que se necesita representar la ciudad en forma de estructura de datos, pero no se pide explícitamente que la lógica de negocio se implemente en este punto (en nuestro caso, la búsqueda de una ruta optima). ¿Qué es lo que no sirve de lo propuesto hasta ahora? Al crear las estructuras de datos actuales estamos intentando almacenar los datos que se usarán posteriormente para desarrollar la lógica de negocio. 

Llegados a este punto me encuentro un poco perdido y quiero continuar avanzado, lo siento si la duda propuesta tiene una respuesta demasiado obvia pero ahora mismo no lo veo. Igualmente voy a volver a repasar todo lo comentado y a buscar una solución.

**Comment by pedrooot** [comment]
Si te quieres centrar en la representación de la ciudad en forma de estructura de datos sin tocar la lógica de negocio vas por el buen camino. Lo único que encuentro innecesario es el atributo matrícula de vehículo de la ruta. Trata de implementar todo lo que hay en los issues y después vemos si hay algún problema y abrimos issue para solucionarlo.

**Comment by JaimeGM96** [comment]
A la hora de calcular la Ruta, no será necesario saber la matricula concreta de un Vehículo. Necesitaremos su información relevante para la toma de decisiones. Esto es la antigüedad, ya que en muchas ciudades no se permite el transito a vehículos altamente contaminantes y que tengan muchos años es un motivo de que pueda contaminar más, y el consumo medio. Esto último serviría para conocer cuál es la ruta optima en cuanto a consumo pero no en cuanto a tiempo, me explico:
- En ciudad se consume más combustible debido a que se usan marchas más cortas y se producen más acelerones al tener que parar y arrancar. 
- En cuanto a la autovía, al llevar un ritmo constante, el consumo es menor.

Si el objetivo del proyecto es únicamente la optimización por tiempo, este atributo tampoco nos serviría. Volviendo a leer la información proporcionada en las historias de usuario [HU1](https://github.com/pedromarting3/OnTime/issues/5) y [HU2](https://github.com/pedromarting3/OnTime/issues/6), sólo se describe el problema del tiempo por lo tanto, el atributo consumo no sería necesario.

**Comment by JaimeGM96** [comment]
> Tal y como se describe en el milestone [M1](https://github.com/pedromarting3/OnTime/milestone/1) se necesitan unas estructuras de datos para representar el modelo de la ciudad. Fijandonos en lo que se comenta en las historias de usuario #5 y #6 una de ellas puede ser una Ruta. ¿Cómo sería la estructura de una Ruta?

¿Que entendemos por Ruta? @pedromarting3

**Comment by JJ** [comment]
> > Tal y como se describe en el milestone [M1](https://github.com/pedromarting3/OnTime/milestone/1) se necesitan unas estructuras de datos para representar el modelo de la ciudad. Fijandonos en lo que se comenta en las historias de usuario #5 y #6 una de ellas puede ser una Ruta. ¿Cómo sería la estructura de una Ruta?
> 
> ¿Que entendemos por Ruta? @pedromarting3

¿Qué dice la lógica de negocio? ¿Qué dice el milestone? ¿Qué entiendes *tú* por ruta una vez que apliques domain driven design?
