### ISSUE TITLE
[HU1] ¿Qué es un Tramo?

### ISSUE THREAD

**Issue by JaimeGM96** [pedrooot/OnTime#20]
Como ya se ha comentado en el issue #10, viendo lo descrito en el milestone [M1](https://github.com/pedromarting3/OnTime/milestone/1) se necesitan unas estructuras de datos para representar el modelo de la ciudad. Tras analizar las historias de usuario https://github.com/pedromarting3/OnTime/issues/5 y https://github.com/pedromarting3/OnTime/issues/6 el siguiente modelo a representar puede ser un Tramo. ¿Cómo sería la estructura de un Tramo?

**Comment by JaimeGM96** [comment]
La estructura que podría representar un Tramo sería la siguiente:

- Id identificador del tramo
- Origen punto de origen del tramo
- Destino punto de destino del tramo
- Distancia distancia total del tramo
- Consumo medio consumo medio del tramo
- Tiempo medio tiempo medio que se tarda en completar el tramo
- Hora de inicio hora de inicio en el día

Con esto se podría completar la información necesaria de la Ruta ya que nos permitiría elegir los mejores tramos que formarán la ruta.

**Comment by JaimeGM96** [comment]
¿A qué te refieres con el último atributo? El de la inicio de hora en el día. El resto tiene buena pinta

_Originally posted by @pedromarting3 in https://github.com/pedromarting3/OnTime/issues/11#issuecomment-1291733496_

**Comment by JaimeGM96** [comment]
Con ese atributo sabremos la hora del día en el que se ha realizado la ruta. No es lo mismo entrar a Granada a las 8 de la mañana que a las 7 de la tarde, el tráfico varia por lo que se tarda más.

**Comment by JaimeGM96** [comment]
Aaaa vale vale perfecto

_Originally posted by @pedromarting3 in https://github.com/pedromarting3/OnTime/issues/11#issuecomment-1291811992_

**Comment by JaimeGM96** [comment]
¿Es necesario que en el tramo esté el atributo de consumo medio? Teniendo en cuenta que el consumo depende del vehículo y esa información ya está almacenada en él.

**Comment by JaimeGM96** [comment]
Tienes razón, en un futuro podríamos tomar el consumo medio del vehículo y a partir del mismo calcular el consumo del vehículo en determinada ruta/tramo. El atributo consumo medio del tramo no es necesario @JaimeGM96

_Originally posted by @pedromarting3 in https://github.com/pedromarting3/OnTime/issues/11#issuecomment-1294847630_

**Comment by JaimeGM96** [comment]
La clase Tramo que nos queda después de analizar el problema sería la siguiente:

- Id
- Origen
- Destino
- Distancia
- Tiempo medio
- Hora inicio

**Comment by JaimeGM96** [comment]
Propongo que para la clase Tramo se elimine el Id ya que se puede diferenciar un tramo de otro con los atributos origen, destino y hora inicio.

**Comment by JaimeGM96** [comment]
> Como ya se ha comentado en el issue #10, viendo lo descrito en el milestone [M1](https://github.com/pedromarting3/OnTime/milestone/1) se necesitan unas estructuras de datos para representar el modelo de la ciudad. Tras analizar las historias de usuario #5 y #6 el siguiente modelo a representar puede ser un Tramo. ¿Cómo sería la estructura de un Tramo?

@pedromarting3 ¿Qué entiendes que es un Tramo?

**Comment by pedrooot** [comment]
Un tramo es un segmento que une dos paradas en una ruta. Adjunto imagen de ejemplo: 
![Captura de pantalla 2022-11-02 a las 13 37 39](https://user-images.githubusercontent.com/56402503/199491812-56d76cfb-05fe-4b1d-ab5a-aae50f685b98.png)

**Comment by pedrooot** [comment]
Como ves, si partimos del punto azul y vamos en coche, el usuario toma el tramo negro y una vez que llega al cruce (puede escoger entre el ramo verde y el tramo rojo) nuestro servicio determinará cuál es mejor tomar para llegar a cierta localización.  
Imagina que queremos llegar a la ETSIIT, después del negro tendríamos que ir por el verde y después por el morado. Según se ha modelizado, un tramo es un segmento de ruta en el que su inicio y final es un cambio de dirección/calle/desvío.

**Comment by pedrooot** [comment]
![Captura de pantalla 2022-11-02 a las 13 45 36](https://user-images.githubusercontent.com/56402503/199493395-98ddf387-d2e1-4ae7-b92f-d9caf2272480.png)
Ahora es cuando realmente entra nuestro servicio: 
El usuario llega muy justo de tiempo (8:30) y se tiene registro de que a esta hora, el tramo morado es muy lento porque la gente está buscando aparcamiento y es imposible pasar. Nuestro servicio genera una ruta nueva (negro-rojo-amarillo-azul) en vez de la que habría sido más corta a una hora menos concurrida (negro-verde-morado)

**Comment by pedrooot** [comment]
Si no te ha quedado claro me dices 😬
