### ISSUE TITLE
[HU1] ¿Qué es un Vehículo?

### ISSUE THREAD

**Issue by JaimeGM96** [pedrooot/OnTime#21]
Otro de los modelos que se necesitan para representar la estructura de la ciudad comentada en [M1](https://github.com/pedromarting3/OnTime/milestone/1) es el Vehículo.

Ya hemos visto en las historias de usuario [HU1](https://github.com/pedromarting3/OnTime/issues/5) y [HU2](https://github.com/pedromarting3/OnTime/issues/6) que el objetivo es coordinar mejor el tráfico y conociendo bien como son los causantes del problema (Vehículos) se podrá entender y alcanzar la solución.

¿Cuál es la información que se almacenaría de los mismos?

**Comment by JaimeGM96** [comment]
Ya hemos visto como podrían ser tanto la Ruta como los Tramos que la forman pero no es lo mismo una moto que un camión a la hora de recorrer una Ruta, tanto por el consumo como la disponibilidad de pasar por según que zonas. Por eso sería interesante crear una clase Vehiculo con la siguiente información:

- Matricula identidicador del vehiculo
- Tipo de vehiculo moto, coche, camión, etc
- Antigüedad en según que zonas de una ciudad es posible que por la antigüedad del mismo no pueda pasar, ya que podría ser muy contaminante
- Consumo medio dependiendo del vehiculo consumirá más o menos

**Comment by JaimeGM96** [comment]
Me parece muy buena idea el atributo de la antigüedad pero si realmente quieres implementarlo así también tendríamos que manejarlo de alguna forma en la ruta/tramos para determinar la edad de los vehículos que pueden entrar en los mismos. Esto hace referencia a #10 y #11

_Originally posted by @pedromarting3 in https://github.com/pedromarting3/OnTime/issues/12#issuecomment-1291740561_

**Comment by JaimeGM96** [comment]
Podríamos poner como referencia en la clase Tramo el vehículo para poder obtener así sus datos. Con ponerlo en la clase Tramo sería suficiente porque es donde se necesita saber cual elegir.

**Comment by JaimeGM96** [comment]
Te entiendo, además una ruta puede tener tramos que pertenezcan a una antigüedad, otros a otra...  
Concuerdo contigo @JaimeGM96 !!

_Originally posted by @pedromarting3 in https://github.com/pedromarting3/OnTime/issues/12#issuecomment-1291814403_

**Comment by JaimeGM96** [comment]
La clase Vehículo quedaría finalmente de la siguiente forma:

- Matricula
- Antigüedad
- Consumo medio

**Comment by JaimeGM96** [comment]
Nos interesa conocer los datos del Vehículo relevantes a la hora de tomar decisiones. La matrícula no es uno de ellos. Por lo tanto se ha eliminado el atributo.

**Comment by JaimeGM96** [comment]
Teniendo en cuenta lo comentado en el issue #19: 
        A la hora de calcular la Ruta, no será necesario saber la matricula concreta de un Vehículo. Necesitaremos su información relevante para la toma de decisiones. Esto es la antigüedad, ya que en muchas ciudades no se permite el transito a vehículos altamente contaminantes y que tengan muchos años es un motivo de que pueda contaminar más, y el consumo medio. Esto último serviría para conocer cuál es la ruta optima en cuanto a consumo pero no en cuanto a tiempo, me explico:
- En ciudad se consume más combustible debido a que se usan marchas más cortas y se producen más acelerones al tener que parar y arrancar. 
- En cuanto a la autovía, al llevar un ritmo constante, el consumo es menor.

Si el objetivo del proyecto es únicamente la optimización por tiempo, este atributo tampoco nos serviría. Volviendo a leer la información proporcionada en las historias de usuario [HU1](https://github.com/pedromarting3/OnTime/issues/5) y [HU2](https://github.com/pedromarting3/OnTime/issues/6), sólo se describe el problema del tiempo por lo tanto, el atributo consumo no sería necesario.

_Originally posted by @JaimeGM96 in https://github.com/pedromarting3/OnTime/issues/19#issuecomment-1296233365_

Una clase Vehículo con tan solo un atributo puede no ser necesaria para el desarrollo de la solución al problema que se nos plantea. Por lo tanto, voy a trasladar el atributo antigüedad de la clase actual a la Ruta ya que considero que es mejor tenerlo almacenado en esa estructura y prescindir del Vehículo.

**Comment by pedrooot** [comment]
Buenas Jaime, revisando[ las historias de usuario](https://github.com/pedromarting3/OnTime/blob/main/docs/Personas.md) he recordado que Yolanda requería que la información de los trayectos que realiza su vehículo. Lo siento porque esto es culpa mía, en su momento actualicé el personas.md pero no toqué el issue #5. Después de esto, deberíamos de reconsiderar tener una clase usuario.  
De verdad que lo siento porque sé que estás poniendo mucho empeño y ha sido fallo mío pero hay que revisarlo.

**Comment by JaimeGM96** [comment]
No te preocupes, no pasa nada, estamos para aprender 💪🏻. Creo un issue para ver qué es lo que necesitamos de un Usuario y seguimos avanzando.

**Comment by JJ** [comment]
La entrada a las zonas no se hace por antigüedad, sino por calificación.
