### ISSUE TITLE
[HU1] ¿Qué información necesitamos almacenar?

### ISSUE THREAD

**Issue by JaimeGM96** [pedrooot/OnTime#23]
Como se ha comentado en https://github.com/pedromarting3/OnTime/issues/21#issuecomment-1296248264, la historia de usuario [HU1](https://github.com/pedromarting3/OnTime/issues/5) y más concretamente en el documento [personas.md](https://github.com/pedromarting3/OnTime/blob/main/docs/Personas.md) hace referencia a que la información de los trayectos que ha realizado se almacenan y pueden consultarse cuando sea pero, no disponemos de nada para almacenar esa información y lo más importante, ¿qué información tenemos que almacenar?

**Comment by JaimeGM96** [comment]
Los datos de interés son las Rutas que se han realizado y esa información podría quedar recogida en un Usuario. Un posible identificador podría ser el email del usuario.

**Comment by JaimeGM96** [comment]
He pensado que el identificador sea el email del usuario por varias razones:
- Es algo único de cada usuario y no lleva a confusión saber a quien pertenece.
- La matricula del coche que conduce podría no ser siempre la misma, es decir, podría o renovar el vehículo o simplemente tener varios.

**Comment by pedrooot** [comment]
Concuerdo contigo @JaimeGM96, respecto a la información que debemos de almacenar es la siguiente:  
* Tiempo en el que se tarda hacer una ruta 
* Consumo medio
* Hora en la que se realiza

Ya me dices si piensas que sobra o falta algo.

**Comment by JaimeGM96** [comment]
Si es solo para optimización de tiempo, creo que el consumo medio no nos interesa mucho. Si también queremos optimizar el consumo, es una buena medida a tener en cuenta.
Por otro lado, si que creo que es mejor almacenar sólo el tiempo y la hora de inicio de una ruta en vez de la Ruta entera ya que así conseguimos optimizar el código. También creo que podría ser útil almacenar el nombre de la ruta para saber a qué Ruta se refieren los datos que hemos guardado.

**Comment by JaimeGM96** [comment]
No estoy muy familiarizado con JavaScript por lo que no se si lo que he implementado es correcto. Para almacenar la información de las rutas, el atributo infoRuta he pensado que puede ser un Array de Maps. He visto que los Maps son diccionarios con su clave valor. Con esto habría 3 claves (nombre, tiempoMedio y horaInicio) con sus respectivos valores. Como cada Usuario va a realizar más de una Ruta, se necesitan almacenar muchos Maps como el que acabo de nombrar, por lo que lo almacenaría en un array. 

Si esta distribución no es correcta o ya hay algo en JavaScript que lo implemente de forma nativa (puede que con el propio Map se pueda hacer), lo cambiamos 👍🏼

**Comment by pedrooot** [comment]
Perfecto Jaime, tiene bastante buena pinta. Si no te importa nos esperamos a mañana por si se nos ocurre algo mejor o que falte y ya mencionamos a JJ😬

**Comment by JaimeGM96** [comment]
Perfecto 👍🏼

**Comment by pedrooot** [comment]
@JaimeGM96 a ver que opina JJ, solicita revisión

**Comment by JJ** [comment]
> No estoy muy familiarizado con JavaScript por lo que no se si lo que he implementado es correcto. Para almacenar la información de las rutas, el atributo infoRuta he pensado que puede ser un Array de Maps. He visto que los Maps son diccionarios con su clave valor. Con esto habría 3 claves (nombre, tiempoMedio y horaInicio) con sus respectivos valores. Como cada Usuario va a realizar más de una Ruta, se necesitan almacenar muchos Maps como el que acabo de nombrar, por lo que lo almacenaría en un array.
> 
> Si esta distribución no es correcta o ya hay algo en JavaScript que lo implemente de forma nativa (puede que con el propio Map se pueda hacer), lo cambiamos 👍🏼

Os rogaría que hiciérais un mínimo esfuerzo por intentar entender qué es el domain driven design y por qué es importante para este objetivo. Se trata de tomar cosas del dominio, e interpretarlos en clave de solución del problema como entidades, objetos-valor o agregados. 

A la vez, esto te va a decir qué es lo que tienes que usar para representar un objeto. Estás diciendo que los Map son "diccionarios clave-valor". ¿Sabes qué es también un diccionario clave valor? Un objeto en Javascript. Objeto que podías haber deducido usando domain driven design.

Os recuerdo una vez más que no se trata de "proponer" cosas y que se aprueben. Se trata de hacer un análisis de las necesidades de la lógica de negocio y "proponer" código, que, ese sí, se tiene que aprobar.

**Comment by JaimeGM96** [comment]
> Como se ha comentado en [#21 (comment)](https://github.com/pedromarting3/OnTime/issues/21#issuecomment-1296248264), la historia de usuario [HU1](https://github.com/pedromarting3/OnTime/issues/5) y más concretamente en el documento [personas.md](https://github.com/pedromarting3/OnTime/blob/main/docs/Personas.md) hace referencia a que la información de los trayectos que ha realizado se almacenan y pueden consultarse cuando sea pero, no disponemos de nada para almacenar esa información y lo más importante, ¿qué información tenemos que almacenar?

@pedromarting3

**Comment by JJ** [comment]
> > Como se ha comentado en [#21 (comment)](https://github.com/pedromarting3/OnTime/issues/21#issuecomment-1296248264), la historia de usuario [HU1](https://github.com/pedromarting3/OnTime/issues/5) y más concretamente en el documento [personas.md](https://github.com/pedromarting3/OnTime/blob/main/docs/Personas.md) hace referencia a que la información de los trayectos que ha realizado se almacenan y pueden consultarse cuando sea pero, no disponemos de nada para almacenar esa información y lo más importante, ¿qué información tenemos que almacenar?
> 
> @pedromarting3

A  @pedromarting3 le cuesta el mismo trabajo contestarte que hacerlo él. Si esa fuera la buena práctica, resultaría en una pérdida de tiempo y dinero para la empresa que la usara.

Eres *tú* el que tienes que decidir qué información almacenar, *creando un modelo del problema que permita aplicar la lógica de negocio*, para superar **tu propio objetivo**, que es el 2. Si @pedromarting3 no ha incluido información suficiente en la descripción de la lógica de negocio, las HUs o los milestones, es eso lo que tienes que hablar o solicitar aclaración, o directametne proponer una solución en código, que @pedromarting3 tendrá entonces que aprobar.

En resumen: si no sabes qué información tienes que almacenar ve a donde se describe la lógica de negocio y abre un issue donde diga cuál es el problema. Una vez abierto, plantea una solución y *entonces* @pedromarting3 podrá decir si está OK o no, o tiene que modificar la descripción de la lógica de negocio.

**Comment by pedrooot** [comment]
He hecho aclaraciones sobre los tramos y la lógica de negocio en #20
