### ISSUE TITLE
Problemas con M1

### ISSUE THREAD

**Issue by JJ** [pedrooot/OnTime#24]
El [M1](https://github.com/pedromarting3/OnTime/milestone/1), tal como está aprobado por mi, presenta diferentes problemas como se ve en la falta de dirección que provee a la persona que está tratando de crear código para él. (Véase #19 #23 y otros)
1. Debería ser M0, no M1
2. Está diciendo de antemano que se trata de un modelo *de la ciudad* no del *problema*
3. Debería clarificar, o al menos enlazar, la descripción de la lógica de negocio que aclare cómo se va a procesar ese modelo del problema para obtener soluciones.

**Comment by pedrooot** [comment]
Ya he modificado el M0, he dado una descripción más extensa para que se entienda mejor @JJ @JaimeGM96

**Comment by JJ** [comment]
Cuando puedas, cambia también la descripción en el texto y cierra esto con un commit.

**Comment by pedrooot** [comment]
Perfecto, se me había pasado 👍🏻
