### ISSUE TITLE
[Objetivo 4] Creación de los test 

### ISSUE THREAD

**Issue by pedrooot** [pedrooot/OnTime#29]
Los test que se van a implementar harán las siguientes funciones:  
* Check de atributos de los objetos después de usar el constructor de diferentes clases
* Check de la creación de las combinaciones posibles dependiendo de InfoTramo
* Check de la salida de la función que implementa la lógica de negocio

**Comment by JJ** [comment]
Los tests son intrínsecos a los problemas que quieres resolver. No puedes tener un issue específico para ellos, porque tampoco plantea un problema.
