### ISSUE TITLE
Elección de lenguaje de programación

### ISSUE THREAD

**Issue by JaimeGM96** [pedrooot/OnTime#7]
Para poder empezar con el desarrollo de la [[HU2](https://github.com/pedromarting3/OnTime/issues/6)], para así avanzar en el [[M1](https://github.com/pedromarting3/OnTime/milestone/1)], primero es necesario saber qué lenguaje de programación se va a usar. Para ello, te pido que me indiques cuál has decidido que puede ser el más idóneo para usar.

**Comment by pedrooot** [comment]
Buenas Jaime, perdón por no contestar antes.  
He pensado utilizar Node, me gustaría saber tu opinión al respecto. Si has tenido una mala experiencia con este lenguaje o no te gusta, no tendría problema en cambiarlo.

**Comment by JaimeGM96** [comment]
Sin problema, usamos node.js.
