### ISSUE TITLE
Creación inicial de las esctructuras de datos

### ISSUE THREAD

**Issue by JaimeGM96** [pedrooot/OnTime#9]
A partir de la documentación aportada en el repositorio de este proyecto, se van a desarrollar las estructuras de datos, y así avanzar en la [[HU2](https://github.com/pedromarting3/OnTime/issues/6)],  que he pensado pueden ser las siguientes:
- Clase Vehículo con los atributos consumo medio, distancia recorrida.
- Clase Ruta con el atributo nº de paradas.
- Clase Usuario que será el que utilice el servicio.

**Comment by JaimeGM96** [comment]
Hola @pedromarting3, he creado este issue para comentar cuales podrían ser las estructuras de datos del proyecto. Estas son las que he visto que podrían ser útiles. Si tienes alguna sugerencia no dudes en decírmelo.

**Comment by pedrooot** [comment]
Buenas @JaimeGM96 en general me parece todo bien, pero pienso que añadir una clase "tramo" nos vendría muy bien. Esta clase tendría como atributos:  
* Consumo medio -> Determinaría el consumo medio del tramo.
* Origen y destino del tramo.
* Tiempo medio -> Tiempo que se tarda en recorrer el tramo.  

Una clase ruta estaría compuesta por un conjunto de tramos.  
Dime tu opinión al respecto y seguimos avanzando!

**Comment by JaimeGM96** [comment]
Hola @pedromarting3, añado también esa clase que comentas. Me pongo a programarlas y cuando suba todo seguimos comentando por si hace falta hacer algún cambio.

**Comment by JJ** [comment]
Esto es una tarea, no un problema. Y ni siquiera hay uno independiente por cada clase. No hay ningún análisis dirigido por el dominio para llevar a cabo esta tarea.

**Comment by JaimeGM96** [comment]
Hola @pedromarting3, perdón por la tardanza en contestar pero me ha sido imposible hacerlo antes. He creado nuevos issues #10 #11 #12 donde se aborda cuales podrían ser la diferentes clases necesarias en el proyecto. Una vez decidamos si esas clases son necesarias y/o que atributos también lo son, pasaré a codificarlo.

**Comment by pedrooot** [comment]
Perfecto @JaimeGM96 te respondo en un segundo. A ello!

**Comment by JaimeGM96** [comment]
¿@pedromarting3, ves necesaria la implementación de una clase Usuario?

**Comment by JJ** [comment]
> ¿@pedromarting3, ves necesaria la implementación de una clase Usuario?

Por favor, dejadme que os explique una vez más que lo que se haga o no no depende de lo que vea necesario una persona del equipo, o el product manager, o quien sea. Si fuera así sería un caos y nadie sabría ni qué hay que hacer ni si lo que hace está bien; si la única guía es si lo ve "bien" alguien o no nos hemos cargado la ingeniería.

En general, debes
1. Mirar las historias de usuario y la descripción del problema, que incluye la lógica de negocio.
2. Ver qué historias de usuario están inscritas en el milestone actual.
3. Crear issues, enlazados a esas historias de usuario, que digan qué problemas hay para convertir las historias de usuario en un modelo del problema. **No** hay que esperar a que el product manager conteste. Nunca hay soluciones que estén "bien" o no. Hay diferentes soluciones, con diferentes ventajas y problemas.
4. Incluir código en el PR, *siempre* refiriéndose al issue creado, que aporte soluciones. *En ese momento* es cuando la persona tiene que decidir si está bien o no, siempre en el mismo marco de milestone e historia de usuario. Si la HU no está bien, tendrá esa persona que cambiarlo, pero la persona que programa *siempre* se tiene que guiar por los issues e HUs.

**Comment by pedrooot** [comment]
Lo llevo un tiempo pensando y desde mi punto de vista no es necesaria la creación de un "usuario". Al final un usuario usa un determinado vehículo así que podríamos enfocar el problema en que estamos generando rutas para el mismo.

**Comment by JaimeGM96** [comment]
Yo también lo he estado pensando y no veo que la clase Usuario sea necesaria para la resolución del problema que tenemos.
